apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: system
  labels:
    app.kubernetes.io/name: pdb-operator
    app.kubernetes.io/component: webhook
    app.kubernetes.io/managed-by: kustomize
spec:
  ports:
  - port: 443
    targetPort: 9443
    protocol: TCP
    name: https
  selector:
    control-plane: controller-manager
    app.kubernetes.io/name: pdb-operator
